### ISSUE TITLE
HPC: Gridsearch

### ISSUE THREAD

**Issue by jxnl** [jxnl/TwitterAlcoholDetection#12]
I'd like the scrip to be designed in the following way.

a class should take the pipeline and gridparams and do anything so the script can simply look like the following.

``` python

params = ...
clf = AlcoholIPipeline.get_pipeline(features["text"])

if __name__ == "__main__"
   job = HPCGridSearch(clfs, params)
   job.run()
```

**Comment by jxnl** [comment]
one way to avoid the question of how to include the features is to grid search the weights themselves.

I'm a genius.

**Comment by jxnl** [comment]
### TODO
- [ ] migrate to HPC
- [ ] define params to search
- [ ] write HPC/MERCER Scripts
- [ ] clear `dbc`
- [ ] run jobs multiple times.

**Comment by rumichunara** [comment]
Thanks for the updates!

**Comment by jxnl** [comment]
so the code is there, 

I'm currently running the feature search on my laptop since its not implemented on the version of sklearn on hpc.

tomorrow I will write the script to run the jobs on hpc.

**Comment by rumichunara** [comment]
Great - let me know if I should message the HPC folks to upgrade, if that will help you going forward

**Comment by jxnl** [comment]
Its not so much an upgrade.

The feature isn’t out yet, so I cloned the github repo and installed from master. 
Basically installing the pre-release. 

It won’t be too much of a concern since i can validate whether or not nonlinear classifiers can boost performance on my laptop.

—

**Comment by jxnl** [comment]
```
#!/bin/bash

#PBS -l nodes=1:ppn=12
#PBS -l walltime=4:00:00
#PBS -l mem=32GB
#PBS -N popcorn
#PBS -M jl7500@nyu.edu
#PBS -m abe

module purge
module load python3
module load scikit-learn.
module load scipy
module load pandas

SRCDIR=$HOME/Twispy/scripts/

RUNDIR=$SCRATCH/Twsipy/run-${PBS_JOBID/.*}
mkdir -p $RUNDIR

# python /home/jl7500/Twipsy/scripts/gridsearch_linearsvc.py
# python /home/jl7500/Twipsy/scripts/gridsearch_logisticregression.py
# python /home/jl7500/Twipsy/scripts/gridsearch_rf.py
# python /home/jl7500/Twipsy/scripts/gridsearch_svc.py
```
